# Generated by Django 5.1.1 on 2024-09-18 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Textmainpg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titile_name', models.CharField(max_length=17)),
                ('body_title', models.TextField(max_length=200)),
            ],
        ),
    ]
