# Generated by Django 5.1.1 on 2024-09-18 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textmainpg',
            name='titile_name',
        ),
        migrations.AddField(
            model_name='textmainpg',
            name='title_name',
            field=models.CharField(default='Defult Title', max_length=100),
        ),
        migrations.AlterField(
            model_name='textmainpg',
            name='body_title',
            field=models.TextField(),
        ),
    ]
