# Generated by Django 5.1.1 on 2024-09-18 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_address_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='coutry_name',
            field=models.CharField(max_length=37),
        ),
        migrations.AlterField(
            model_name='address',
            name='state_ad',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='address',
            name='street_ad',
            field=models.CharField(max_length=50),
        ),
    ]
