# Generated by Django 5.1.1 on 2024-09-18 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_address_coutry_name_alter_address_state_ad_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
