# Generated by Django 5.1.1 on 2024-09-18 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_delete_location'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Address',
            new_name='MainAddres',
        ),
    ]
