# Generated by Django 5.1.1 on 2024-09-18 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_address_mainaddres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainaddres',
            name='coutry_name',
        ),
        migrations.RemoveField(
            model_name='mainaddres',
            name='state_ad',
        ),
    ]
