# Generated by Django 5.1.1 on 2024-09-18 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_bookproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookproduct',
            name='prod_img',
        ),
    ]
