# Generated by Django 5.1.1 on 2024-09-18 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_remove_bookproduct_prod_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookproduct',
            name='prod_name',
            field=models.TextField(max_length=35),
        ),
    ]
