# Generated by Django 5.1.1 on 2024-09-19 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_bookproduct_active_bookproduct_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BooksList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_img', models.ImageField(blank=True, null=True, upload_to='photos/%y/%m/%d')),
                ('book_name', models.TextField(max_length=35)),
                ('book_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
