# Generated by Django 5.1.1 on 2024-09-19 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_bookslist'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookslist',
            name='book_disc',
            field=models.CharField(default='Discription', max_length=25),
        ),
        migrations.AlterField(
            model_name='bookslist',
            name='book_name',
            field=models.CharField(default='Book_name', max_length=12),
        ),
    ]
