# Generated by Django 5.1.1 on 2024-09-19 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_remove_bookslist_book_disc'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookproduct',
            name='book_detail',
            field=models.CharField(default='detail', max_length=25),
        ),
        migrations.AddField(
            model_name='bookslist',
            name='book_disc',
            field=models.CharField(default='detail', max_length=25),
        ),
        migrations.AlterField(
            model_name='bookproduct',
            name='prod_name',
            field=models.CharField(default='book_name', max_length=35),
        ),
    ]
