# Generated by Django 5.1.1 on 2024-09-19 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_bookproduct_book_detail_bookslist_book_disc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookproduct',
            name='book_catagory',
            field=models.CharField(choices=[('action', 'Action'), ('fiction', 'Fiction'), ('non_fiction', 'Non-Fiction'), ('science_fiction', 'Science Fiction'), ('fantasy', 'Fantasy'), ('poetry', 'Poetry'), ('business', 'Business'), ('health_wellness', 'Health & Wellness'), ('travel', 'Travel'), ('cooking', 'Cooking'), ('education', 'Education')], max_length=50, null=True),
        ),
    ]
