# Generated by Django 5.1.1 on 2024-09-19 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_bookproduct_book_catagory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookproduct',
            name='prod_time',
        ),
        migrations.AddField(
            model_name='bookproduct',
            name='author',
            field=models.CharField(default='Author name', max_length=14),
        ),
    ]
