# Generated by Django 5.1.1 on 2024-09-19 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_remove_bookproduct_prod_time_bookproduct_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookproduct',
            name='book_detail',
            field=models.CharField(max_length=25, verbose_name='detail'),
        ),
        migrations.AlterField(
            model_name='bookproduct',
            name='prod_name',
            field=models.CharField(max_length=35, verbose_name='book_name'),
        ),
    ]
